# Generated by Django 4.2 on 2023-05-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_calendarevent_chatroom_classroom_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
