from django.urls import path
from .views import (
    index,
    user_login,
    user_logout,
    TeacherListView,
    TeacherDetailView,
    TeacherCreateView,
    TeacherUpdateView,
    TeacherDeleteView,
    ParentListView,
    ParentDetailView,
    ParentCreateView,
    ParentUpdateView,
    ParentDeleteView,
    StudentListView,
    StudentDetailView,
    StudentCreateView,
    StudentUpdateView,
    StudentDeleteView,
    AdminListView,
    AdminDetailView,
    AdminCreateView,
    AdminUpdateView,
    CourseListView, 
    CourseDetailView,
    StudentPerformanceListView,
    StudentPerformanceDetailView,
    StudentPerformanceCreateView,
    StudentPerformanceUpdateView,
    StudentPerformanceDeleteView,
)
app_name = "administration"

urlpatterns = [
    
    path("", index, name="index"),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('teachers/', TeacherListView.as_view(), name='teacher_list'),
    path('teachers/<int:pk>/', TeacherDetailView.as_view(), name='teacher_detail'),
    path('teachers/create/', TeacherCreateView.as_view(), name='teacher_create'),
    path('teachers/update/<int:pk>/', TeacherUpdateView.as_view(), name='teacher_update'),
    path('teachers/delete/<int:pk>/', TeacherDeleteView.as_view(), name='teacher_delete'),
    path('parents/', ParentListView.as_view(), name='parent_list'),
    path('parents/<int:pk>/', ParentDetailView.as_view(), name='parent_detail'),
    path('parents/create/', ParentCreateView.as_view(), name='parent_create'),
    path('parents/update/<int:pk>/', ParentUpdateView.as_view(), name='parent_update'),
    path('parents/delete/<int:pk>/', ParentDeleteView.as_view(), name='parent_delete'),
    path('students/', StudentListView.as_view(), name='student_list'),
    path('students/<int:pk>/', StudentDetailView.as_view(), name='student_detail'),
    path('students/create/', StudentCreateView.as_view(), name='student_create'),
    path('students/update/<int:pk>/', StudentUpdateView.as_view(), name='student_update'),
    path('students/delete/<int:pk>/', StudentDeleteView.as_view(), name='student_delete'),
    path('admins/', AdminListView.as_view(), name='admin_list'),
    path('admins/<int:pk>/', AdminDetailView.as_view(), name='admin_detail'),
    path('admins/create/', AdminCreateView.as_view(), name='admin_create'),
    path('admins/update/<int:pk>/', AdminUpdateView.as_view(), name='admin_update'),
    path('courses/', CourseListView.as_view(), name='course_list'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course_detail'),
]
